import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { v4 as uuidv4 } from 'uuid'; // For generating unique filenames

const MINIO_ENDPOINT = process.env.NEXT_PUBLIC_MINIO_ENDPOINT || "http://localhost:9000";
const MINIO_ACCESS_KEY = process.env.NEXT_PUBLIC_MINIO_ACCESS_KEY || "ak-123456"; // Get from .env
const MINIO_SECRET_KEY = process.env.NEXT_PUBLIC_MINIO_SECRET_KEY || "sk-123456"; // Get from .env
const MINIO_BUCKET_NAME = process.env.NEXT_PUBLIC_MINIO_BUCKET_NAME || "images";
const MINIO_REGION = process.env.NEXT_PUBLIC_MINIO_REGION || "us-east-1"; // MinIO is region-agnostic but SDK might require one

// IMPORTANT: For client-side usage, ensure these credentials are for a user with
// *limited permissions* (e.g., only PutObject to a specific bucket/path).
// Exposing root credentials client-side is a security risk.
// For this local setup, we're using root keys, but this is NOT for production.
// In production, consider presigned URLs generated by your backend.

const s3Client = new S3Client({
    endpoint: MINIO_ENDPOINT,
    region: MINIO_REGION,
    credentials: {
        accessKeyId: MINIO_ACCESS_KEY,
        secretAccessKey: MINIO_SECRET_KEY,
    },
    forcePathStyle: true, // Required for MinIO
});

export const uploadFileToMinio = async (file: File): Promise<string> => {
    if (!file) {
        throw new Error("No file provided for upload.");
    }

    // Generate a unique key for the S3 object (e.g., using UUID and original extension)
    const fileExtension = file.name.split('.').pop();
    const uniqueFileName = `${uuidv4()}.${fileExtension}`;
    const objectKey = `uploads/${uniqueFileName}`; // Optional: organize in a subfolder

    // Read file as ArrayBuffer
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);

    const params = {
        Bucket: MINIO_BUCKET_NAME,
        Key: objectKey,
        Body: uint8Array, // Use Uint8Array
        ContentType: file.type,
        // ACL: 'public-read', // Not needed if bucket policy is public-read
    };

    try {
        const command = new PutObjectCommand(params);
        await s3Client.send(command);

        // Construct the public URL
        // This assumes the bucket has a public read policy set.
        const publicUrl = `${MINIO_ENDPOINT}/${MINIO_BUCKET_NAME}/${objectKey}`;
        console.log("File uploaded successfully:", publicUrl);
        return publicUrl;
    } catch (error) {
        console.error("Error uploading file to MinIO:", error);
        throw new Error(`Failed to upload file: ${error instanceof Error ? error.message : String(error)}`);
    }
};